import { useState } from 'react';
import { FileText, Download, CheckCircle, Clock, TrendingUp } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import jsPDF from 'jspdf';
import { formatCurrency } from '../../utils/formatCurrency';

const data = [
  { name: 'Jan', students: 1200, revenue: 45000 },
  { name: 'Feb', students: 1250, revenue: 48000 },
  { name: 'Mar', students: 1248, revenue: 52000 },
];

const ReportsPage = () => {
  const [notification, setNotification] = useState<string | null>(null);

  const handleExportAll = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text('Institutional Performance Report 2026', 14, 20);
    doc.setFontSize(12);
    doc.text(`Total Students: 1,248`, 14, 35);
    doc.text(`Total Revenue (YTD): ${formatCurrency('145,000')}`, 14, 45);
    doc.text(`Generated by: Administrator`, 14, 55);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 65);
    
    doc.setFontSize(16);
    doc.text('Summary Statistics', 14, 85);
    doc.setFontSize(10);
    doc.text('1. Student Enrollment: 4.2% Growth from Q4 2025', 20, 95);
    doc.text('2. Fee Collection: 92% Completion Rate', 20, 105);
    doc.text('3. Attendance: 94.2% Average Daily Attendance', 20, 115);

    doc.save('institutional_full_report.pdf');
    setNotification('Cumulative report generated and downloaded!');
    setTimeout(() => setNotification(null), 3000);
  };

  return (
    <div className="space-y-6 lg:pb-12 h-full">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Institutional Reports</h1>
          <p className="text-slate-500">Analyze performance, attendance, and financial trends.</p>
        </div>
        <button 
          onClick={handleExportAll}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 border border-indigo-500 rounded-xl font-bold text-white hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-600/20 text-sm active:scale-95"
        >
           <Download size={16} /> Export All (PDF)
        </button>
      </div>

      {notification && (
        <div className="fixed top-20 right-6 z-50 animate-in slide-in-from-right fade-in duration-300">
          <div className="bg-slate-900 text-white px-6 py-4 rounded-2xl shadow-xl flex items-center gap-3 border border-slate-800">
            <CheckCircle size={20} className="text-indigo-400" />
            <p className="font-semibold text-sm">{notification}</p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 lg:col-span-2">
           <div className="flex items-center justify-between mb-8">
              <h2 className="text-lg font-semibold text-slate-900">Student Growth Trajectory</h2>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-50 text-emerald-600 rounded-lg text-xs font-bold uppercase tracking-wider">
                 <TrendingUp size={14} /> +12.4% Rise
              </div>
           </div>
           <div className="h-72">
             <ResponsiveContainer width="100%" height="100%">
               <BarChart data={data}>
                 <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                 <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12}} />
                 <YAxis axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12}} />
                 <Tooltip cursor={{fill: '#f8fafc'}} contentStyle={{borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)'}} />
                 <Bar dataKey="students" fill="#6366f1" radius={[6, 6, 0, 0]} barSize={45} />
               </BarChart>
             </ResponsiveContainer>
           </div>
        </div>
        
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
           <div className="flex items-center justify-between mb-6">
             <h2 className="text-lg font-semibold text-slate-900">Archived Reports</h2>
             <Clock size={18} className="text-slate-400" />
           </div>
           <div className="space-y-4">
              {[
                { title: 'Annual Academic Audit 2025', date: 'March 15, 2026', size: '2.4 MB' },
                { title: 'Q1 Financial Summary', date: 'March 10, 2026', size: '1.1 MB' },
                { title: 'Staff Performance Review', date: 'March 02, 2026', size: '840 KB' },
                { title: 'Student Health Audit', date: 'Feb 24, 2026', size: '1.9 MB' },
              ].map((rpt, i) => (
                <div key={i} className="flex items-center justify-between p-4 border border-slate-100 rounded-xl hover:bg-slate-50 transition-colors cursor-pointer group">
                   <div className="flex items-center gap-3">
                      <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg group-hover:bg-indigo-100 transition-colors">
                        <FileText size={20} />
                      </div>
                      <div>
                        <h4 className="text-sm font-semibold text-slate-900">{rpt.title}</h4>
                        <p className="text-[10px] text-slate-500 font-medium uppercase mt-0.5">{rpt.date} • {rpt.size}</p>
                      </div>
                   </div>
                   <Download size={16} className="text-slate-400 group-hover:text-indigo-600 transition-colors" />
                </div>
              ))}
           </div>
           <button className="w-full mt-6 py-2.5 text-sm font-bold text-indigo-600 border-2 border-dashed border-indigo-100 rounded-xl hover:bg-indigo-50 transition-colors">Generate Custom Range Report</button>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;
