import { useEffect, useMemo, useState } from 'react';
import { FileText, Download, CheckCircle, Clock, TrendingUp } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import jsPDF from 'jspdf';
import { useAuthStore } from '../../store/useAuthStore';
import { useClassStore } from '../../store/useClassStore';
import { fetchAttendanceMonthlyTrend, fetchAttendanceOverview } from '../../services/attendance';

const ReportsPage = () => {
  const { user } = useAuthStore();
  const initialize = useClassStore((state) => state.initialize);
  const students = useClassStore((state) => state.students);
  const sections = useClassStore((state) => state.sections);
  const [notification, setNotification] = useState<string | null>(null);
  const [monthlyTrend, setMonthlyTrend] = useState<Array<{ month: string; records: number; attendanceRate: number }>>([]);
  const [attendanceRate, setAttendanceRate] = useState(0);
  const [presentCount, setPresentCount] = useState(0);
  const [absentCount, setAbsentCount] = useState(0);
  const [totalRecords, setTotalRecords] = useState(0);

  useEffect(() => {
    void initialize();
    void fetchAttendanceMonthlyTrend(6).then(setMonthlyTrend).catch(console.error);
    void fetchAttendanceOverview(30)
      .then((overview) => {
        setAttendanceRate(overview.attendanceRate);
        setPresentCount(overview.presentCount);
        setAbsentCount(overview.absentCount);
        setTotalRecords(overview.totalRecords);
      })
      .catch(console.error);
  }, [initialize]);

  const handleExportAll = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text('Institutional Attendance Report 2026', 14, 20);
    doc.setFontSize(12);
    doc.text(`Total Students: ${students.length}`, 14, 35);
    doc.text(`Active Sections: ${sections.length}`, 14, 45);
    doc.text(`Generated by: ${user?.name || 'Administrator'}`, 14, 55);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 65);

    doc.setFontSize(16);
    doc.text('Attendance Summary', 14, 85);
    doc.setFontSize(10);
    doc.text(`1. Attendance Rate: ${attendanceRate}% over the last 30 days`, 20, 95);
    doc.text(`2. Present Entries Logged: ${presentCount}`, 20, 105);
    doc.text(`3. Absent Entries Logged: ${absentCount}`, 20, 115);
    doc.text(`4. Total Attendance Records: ${totalRecords}`, 20, 125);

    let y = 145;
    doc.setFontSize(14);
    doc.text('Monthly Coverage', 14, y);
    y += 10;
    doc.setFontSize(10);
    monthlyTrend.forEach((item) => {
      doc.text(`${item.month}: ${item.records} records, ${item.attendanceRate}% attendance`, 20, y);
      y += 8;
    });

    doc.save('institutional_attendance_report.pdf');
    setNotification('Attendance report generated and downloaded!');
    setTimeout(() => setNotification(null), 3000);
  };

  const growthText = useMemo(() => {
    if (monthlyTrend.length < 2) {
      return 'Live trend';
    }

    const previous = monthlyTrend[monthlyTrend.length - 2]?.attendanceRate || 0;
    const current = monthlyTrend[monthlyTrend.length - 1]?.attendanceRate || 0;
    const delta = current - previous;

    return `${delta >= 0 ? '+' : ''}${delta}% vs last month`;
  }, [monthlyTrend]);

  return (
    <div className="space-y-6 lg:pb-12 h-full">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Institutional Reports</h1>
          <p className="text-slate-500">Analyze live attendance trends from your database.</p>
        </div>
        <button
          onClick={handleExportAll}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 border border-indigo-500 rounded-xl font-bold text-white hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-600/20 text-sm active:scale-95"
        >
          <Download size={16} /> Export All (PDF)
        </button>
      </div>

      {notification && (
        <div className="fixed top-20 right-6 z-50 animate-in slide-in-from-right fade-in duration-300">
          <div className="bg-slate-900 text-white px-6 py-4 rounded-2xl shadow-xl flex items-center gap-3 border border-slate-800">
            <CheckCircle size={20} className="text-indigo-400" />
            <p className="font-semibold text-sm">{notification}</p>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 lg:col-span-2">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-lg font-semibold text-slate-900">Attendance Records by Month</h2>
            <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-50 text-emerald-600 rounded-lg text-xs font-bold uppercase tracking-wider">
              <TrendingUp size={14} /> {growthText}
            </div>
          </div>
          <div className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={monthlyTrend}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 12 }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fill: '#94a3b8', fontSize: 12 }} />
                <Tooltip cursor={{ fill: '#f8fafc' }} contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }} />
                <Bar dataKey="records" fill="#6366f1" radius={[6, 6, 0, 0]} barSize={45} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-semibold text-slate-900">Live Attendance Summary</h2>
            <Clock size={18} className="text-slate-400" />
          </div>
          <div className="space-y-4">
            {[
              { title: 'Attendance Rate', value: `${attendanceRate}%`, meta: 'Last 30 days' },
              { title: 'Present Entries', value: presentCount.toString(), meta: 'Recorded in DB' },
              { title: 'Absent Entries', value: absentCount.toString(), meta: 'Recorded in DB' },
              { title: 'Total Logs', value: totalRecords.toString(), meta: 'Attendance records' },
            ].map((item) => (
              <div key={item.title} className="flex items-center justify-between p-4 border border-slate-100 rounded-xl hover:bg-slate-50 transition-colors group">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg group-hover:bg-indigo-100 transition-colors">
                    <FileText size={20} />
                  </div>
                  <div>
                    <h4 className="text-sm font-semibold text-slate-900">{item.title}</h4>
                    <p className="text-[10px] text-slate-500 font-medium uppercase mt-0.5">{item.meta}</p>
                  </div>
                </div>
                <span className="text-sm font-bold text-slate-700">{item.value}</span>
              </div>
            ))}
          </div>
          <button className="w-full mt-6 py-2.5 text-sm font-bold text-indigo-600 border-2 border-dashed border-indigo-100 rounded-xl hover:bg-indigo-50 transition-colors">
            Attendance report uses live Supabase data
          </button>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;
